version: "3.8"
services:
  mailer:
    environment:
      - NODE_ENV=development
      - MONGODB_URL=mongodb://mongodb/queuing
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://redis:6379
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/user/app
    container_name: mailer
    depends_on:
      - mongodb
      - redis
    ports:
      - "4000:4000"
    command: npm run prod
    networks:
      - node-network
    links:
      - redis

  redis:
    image: "bitnami/redis:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      - node-network
    container_name: redis

  mongodb:
    image: mongo:4.4.21-focal
    ports:
      - "27017:27017"
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network
    container_name: mongodb

volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge
